### ISSUE TITLE
ERROR: Cannot configure the 'publishing' extension after it has been accessed.

### ISSUE THREAD

**Issue by CaptainRock** [IvBaranov/MaterialFavoriteButton#22]
I have just forked the repository and imported it to Android Studio. The first gradle build has failedwith this error.

ERROR: Cannot configure the 'publishing' extension after it has been accessed.

Gradle Version - 4.4
Gradle Plugin Version - 3.1.4

**Comment by IvBaranov** [comment]
Looks like typical compatibility issue.
 - Latest version of Android Studio is not compatible with `bintray-release` plugin. 
 - Latest version of `bintray-release` plugin supports 4.0+ gradle plugin.
 - Latest version of gradle (6.1.1) has unresolved issues with `bintray-release`, see https://github.com/novoda/bintray-release/issues/318

Right now you can just get rid of release plugin stuff in order to build your working project.

**Comment by CaptainRock** [comment]
Thanks.I will remove the release plugin.
